import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// TODO: componentize
import { auth, providers } from '../config/firebase'

const signUp = () => {
  return auth
    .signInWithPopup(providers.google)
    .then((response) => {
      console.log(response)
    })
    .catch((error) => {
      return { error }
    })
}

const onSubmit = () => {
  return signUp().then((user) => {
    console.log({user})
  })
}
//

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <button onClick={onSubmit}>Iniciar sesión con Google</button>
      </main>

      <footer className={styles.footer}>
        FOOTER
      </footer>
    </div>
  )
}

export default Home
