import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useAuth } from '../hooks/useAuth'

const Home: NextPage = () => {
  const [auth, signOut] = useAuth()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        Bievenido {auth.displayName}
        <button onClick={signOut}>logout</button>
      </main>

      <footer className={styles.footer}>FOOTER</footer>
    </div>
  )
}

export default Home
